<?php
/*
variables de texto para las vistas
*/

namespace front\Controller\Component;

use Cake\Controller\Component;


class TextsComponent extends Component {

	    public function text ($controlador, $vista) {
		
		$espanol  = 
				    	array('Extras' => 				  array(   	//extras
													   	             	'description' => __d('front', 'Descripción'),
													   	             	'empty' => __d('front', 'Seleccióna una opción'),
													   	             	'or' => __d('front', 'O bien'),
													   	             	'avalible' => __d('front', 'Disponible'),
											    	              		'city_state' => __d('front', 'Ciudad'),
											    	              		'city_postal_code' => __d('front', 'Ciudad, Código postal'),
											    	              		'price_from' => __d('front', 'Desde'),
											    	              		'code' => __d('front', 'SC'),
											    	              		'crane_code' => __d('front', 'Código'),
											    	              		'price_until' => __d('front', 'Hasta'),
											    	              		'search_submit' => __d('front', 'Buscar'),
											    	              		'search_company' => __d('front', 'Buscador de empresas'),
											    	              		'company' => __d('front', 'Empresa'),
											    	              		'login_register' => __d('front', 'Iniciar sesión / registrate'),
											    	              		'crane' => __d('front', 'Grúa'),
											    	              		'control_panel' => __d('front', 'Panel de control'),
											    	              		'login_now' => __d('front', 'Inicia sesión ahora'),
											    	              		'register' => __d('front', 'Regístrate ahora'),
											    	              		'dont_have_account' => __d('front', '¿No tienes una cuenta?'),
											    	              		'account' => __d('front', 'Cuenta'),
											    	              		'bussiness_partner' => __d('front', 'Miembros'),
											    	              		'my_account' => __d('front', 'Mi cuenta'),
											    	              		'home' => __d('front', 'Inicio'),
											    	              		'search_title' => __d('front', 'Buscador personalizado'),
											    	              		'post_crane' => __d('front', 'Publica tu grua'),
											    	              		'more_information' => __d('front', 'Más información'),
											    	              		'newsletter' => __d('front', 'Suscríbete'),
											    	              		'about_us' => __d('front', 'Nosotros'),
											    	              		'our_services' => __d('front', 'Servicios'),
											    	              		'contact_us' => __d('front', 'Contáctenos'),
											    	              		'newsletter_email' => __d('front', 'ejemplo@tuemail.com'),
											    	              		'newsletter_button' => __d('front', ''),
											    	              		'follow_us' => __d('front', 'Síguenos'),
											    	              		'phone_usa' => __d('front', 'Teléfono USA'),
											    	              		'coryright' => __d('front', 'Copyright © Todos los derechos reservados.'),
											    	              		'developed_by' => __d('front', 'Diseño y desarollo por'),
											    	              		'speak_seller' => __d('front', 'Habla con el vendedor'),
											    	              		'tender' => __d('front', 'Ofertar'),
											    	              		'generate_alert' => __d('front', 'Alerta generada exitosamente'),
											    	              		'my_offers' => __d('front', 'Mis ofertas'),
											    	              		'my_offer' => __d('front', 'Mi oferta'),
											    	              		'my_offers_description' => __d('front', ''),
											    	              		'change_premium_message' => __d('front', 'Estas usando una cuenta gratuita, cambiate a Premium para obtener todos los beneficios de'),
											    	              		'cookies' => __d('front', 'Uso de cookies en este sitio'),
											    	              		'cookies_acept' => __d('front', 'Acepto el uso de cookies'),
											    	              		'cookies_acept_description' => __d('front', 'El uso de cookies permite a nuestra plataforma guardar información de forma momentanea en su explorador para facilitar y mejorar la experiencia en nuestro sitio web'),
											    	              		'user_already_exist' => __d('front', 'El e-mail ya se encuentra registrado'),
											    	              		'counteroffer' => __d('front', 'Contraoferta'),
											    	              		'tender_placeholder' => __d('front', 'Introduzca su oferta en USD'),
											    	              		'publications' => __d('front', 'Publicaciones'),
											    	              		'profile' => __d('front', 'Tu perfil'),
											    	              		'send_email' => __d('front', 'Mandar Email'),
											    	              		'status' => __d('front', 'Estado'),
											    	              		'active' => __d('front', 'Activa'),
											    	              		'deny' => __d('front', 'Denegada'),
											    	              		'inactive' => __d('front', 'Inactiva'),
											    	              		'forgot_password' => __d('front', '¿olvidó su contraseña?'),
											    	              		'pending' => __d('front', 'Pendiente'),
											    	              		'accept' => __d('front', 'Aceptada'),
											    	              		'loading_info' => __d('front', 'Cargando información'),
											    	              		'avalible_for' => __d('front', 'Disponible para:'),
											    	              		'compare_cranes' => __d('front', 'Comparar Grúas'),
											    	              		'change_premium' => __d('front', 'Cambiate a premium'),
											    	              		'see_profile' => __d('front', 'Revisa tu perfil'),
											    	              		'loading_cities' => __d('front', 'Cargando ciudades...'),
											    	              		'loading' => __d('front', 'Cargando...'),
											    	              		'request_price' => __d('front', 'Ver precio'),
											    	              		'avalible_11' => __d('front', 'Alquiler'),
											    	              		'avalible_12' => __d('front', 'Compra'),
											    	              		'crane_publish' => __d('front', 'Publica tu grúa'),
											    	              		'offer_sucessfull' => __d('front', 'Oferta generada exitósamente'),
											    	              		'user_account_type' => __d('front', 'Tipo de cuenta'),
											    	              		'last_pay_data' => __d('front', 'Datos del último pago realizado'),
											    	              		'offer_sucessfull_relationships' => __d('front', 'Oferta generada exitósamente, se han enviado solicitudes a publicantes relacionados'),

											    	              		'upper_engine' => __d('front', 'Motor grúa'),
											    	              		'vin_number' => __d('front', 'Serial del camión'),
											    	              		'certified' => __d('front', 'Certificada'),
											    	              		'hook_block' => __d('front', 'Gancho pasteca'),
											    	              		'ball' => __d('front', 'Bola'),
											    	              		'winches' => __d('front', 'Winches'),
											    	              		'load_indicator' => __d('front', 'Indicador de carga'),
											    	              		'drive' => __d('front', 'Configuración Ejes'),
											    	              		'axles_number' => __d('front', 'Número de ejes'),
											    	              		'suspension' => __d('front', 'Suspensión'),
											    	              		'front_tire_size' => __d('front', 'Tamaño de las llantas delanteras'),
											    	              		'reference_code' => __d('front', 'Referencia grúa'),
											    	              		'rear_tire_size' => __d('front', 'Tamaño de las llantas traseras'),
											    	              		'daily_rate_with_operator' => __d('front', 'Valor día con operador'),
											    	              		'weekly_rate_with_operator' => __d('front', 'Valor semana con operador'),
											    	              		'monthly_rate_with_operator' => __d('front', 'Valor mes con operador'),
											    	              		'daily_rate_without_operator' => __d('front', 'Valor día sin operador'),
											    	              		'weekly_rate_without_operator' => __d('front', 'Valor semana sin operador'),
											    	              		'monthly_rate_with_operator' => __d('front', 'Valor mes sin operador'),
											    	              		'user_description' => __d('front', 'Descripción corta de la empresa. Ésta información aparecerá en tu micrositio'),
											    	              		'avalible_12' => __d('front', 'Compra'),
											    	              		'avalible_12' => __d('front', 'Compra'),

											    	              		'select_register' => __d('front', 'Selecciona el tipo de registro'),
											    	              		'user_register' => __d('front', 'Registrate como usuario'),
											    	              		'company_register' => __d('front', 'Registrate como empresa'),
											    	              		'company_identification' => __d('front', 'NIT'),
											    	              		'accept_offer' => __d('front', 'Aceptar oferta'),
											    	              		'deny_offer' => __d('front', 'Rechazar oferta'),
											    	              		'pending_offer' => __d('front', 'Oferta pendiente'),
											    	              		'publicity_banner' => __d('front', 'Publicidad'),
											    	              		'sr' =>  __d('front', 'Sr(a)'),
											    	              		'offer_date' =>  __d('front', 'Fecha de repuesta'),

											    	              		//continentes 
											    	              		'america' => __d('front', 'América'),
											    	              		'africa' => __d('front', 'África'),
											    	              		'asia' => __d('front', 'Asia'),
											    	              		'europe' => __d('front', 'Europa'),
											    	              		'oceania' => __d('front', 'Oceanía'),
											    	              		'australia' => __d('front', 'Australia'),
											    	              		'south_america' => __d('front', 'Sur América'),
											    	              		'north_america' => __d('front', 'Norte América'),
											    	              		'premium' => __d('front', 'Premium plan USD'),
											    	              		'professional_plan' => __d('front', 'Professional plan USD'),
											    	              		'banner_rotative' => __d('front', 'Valor banner Premium rotativo USD'),
											    	              		'banner_premium' => __d('front', 'Valor banner + video USD'),
											    	              		'banner_static' => __d('front', 'Valor banner estático USD'),
											    	              		'banner_rotetive_internal' => __d('front', 'Valor banner interno USD'),
											    	              		'banner_rotative_logotype_home' => __d('front', 'Valor banner + logotipo inicio USD'),
											    	              		'plan_banner_rotative' => __d('front', 'Publicidad Bussiness'),
											    	              		'plan_banner_premium' => __d('front', 'Publicidad Premium'),
											    	              		'plan_banner_static' => __d('front', 'Publicidad Basic'),
											    	              		'plan_rotetive_internal' => __d('front', 'Publicidad Interna'),
											    	              		'plan_banner_rotative_logotype_home' => __d('front', 'Publicidad + plus'),

											    	              		//vender comprar grua
											    	              		'sell_crane' => __d('front', 'Ofertar'),
											    	              		'price_request' => __d('front', 'Ver precio'),
											    	              		'rent_crane' => __d('front', 'Rentar'),
											    	              		'sell_crane_description' => __d('front', 'Ingresa la información correspondiente'),
											    	              		'rent_crane' => __d('front', 'Rentar grúa'),
											    	              		'rent_crane_description' => __d('front', 'Por favor, cuéntanos sobre tu proyecto.'),
											    	              		'value' => __d('front', 'Valor en USD'),
											    	              		'counteroffer' => __d('front', 'Contraoferta'),
											    	              		'crane_author' => __d('front', 'Publicante'),
											    	              		'your_offer' => __d('front', 'Descripción del proyecto'),
											    	              		'date_start' => __d('front', 'Fecha inicio proyecto'),
											    	              		'date_end' => __d('front', 'Fecha finalización proyecto'),
											    	              		'require_operator' => __d('front', '¿Requiere Operador?'),
											    	              		'operator' => __d('front', 'Operador'),
											    	              		'quote_bouth_options' => __d('front', 'Cotizar ambas opciones'),
											    	              		'bouth' => __d('front', 'Ambas opciones'),
											    	              		'proyect_country' => __d('front', 'Ubicacion del proyecto, País'),
											    	              		'proyect_city' => __d('front', 'Ubicacion del proyecto, Ciudad'),
											    	              		'proyect_state' =>__d('front', 'Ubicacion del proyecto, Estado'),
											    	              		'proyect_zip_code' => __d('front', 'Ubicacion del proyecto, Código postal'),
											    	              		'yes' => __d('front', 'Si'),
											    	              		'no' => __d('front', 'No'),

											    	              		//ofertas recibidas
											    	              		'recived_offers' => __d('front', 'Ofertas recibidas'),
											    	              		'customer' => __d('front', 'Cliente'),
											    	              		'offer' => __d('front', 'Oferta'),

											    	              		//directorio de empresas
											    	              		'business_directory' => __d('front', 'Directorio empresarial'),
											    	              		'business_directory_description' => __d('front', ''),

											    	              		//iconos inferiores de la descripción (Categorias)
											    	              		'crane_list' => __d('front', 'Listado'),
				    	       											'crane_photos' => __d('front', 'Galería'),
				    	       											'crane_thumbs' => __d('front', 'Miniaturas'),
				    	       											'map' => __d('front', 'Mapa'),	    	       											
				    	       											'map_list' => __d('front', 'Ver/Ocultar mapa'),	    	       											
				    	       											'download_list' => __d('front', 'Descargar'),	
									    	              				'video' => __d('front', 'Video'),		

									    	              				//tipo de industria
									    	              				'industry_type' => __d('front', 'Tipo de industria a la que pertenece'),
									    	              				'industry_type_label' => __d('front', 'Tipo de industria'),
									    	              				'contractor' => __d('front', 'Contratista, Construcción'),
									    	              				'rental_heavy_equipment' => __d('front', 'Alquiler grúas y maquinaria pesada'),
									    	              				'special_transportation' => __d('front', 'Transporte especializado'),
									    	              				'utility_mining_oil' => __d('front', 'Servicios mineria oil & gas'),
									    	              				'new_distrbuitor_parts' => __d('front', 'Distribuidor maquinaria nueva'),
									    	              				'used_distrbuitor_broker' => __d('front', 'Distribuidor Maquinaria Usada'),
									    	              				'windowpower' => __d('front', 'Energia eólica'),
									    	              				'manufacturer' => __d('front', 'Fabricante de equipos de pesaje y transporte'),
									    	              				'server_repair' => __d('front', 'Servicio técnico de grúas'),
									    	              				'certification_company' => __d('front', 'Empresa certificadora & asociaciones'),
									    	              				'others' => __d('front', 'Otros'),

									    	              				//tipo de equipamento
									    	              				'equipment_type' => __d('front', '¿Qué tipo de equipo compra, usa o vende?'),
									    	              				'equipment_new' => __d('front', 'Equipamento nuevo'),
									    	              				'dont_buy_equipment' => __d('front', 'No compro equipamento'),
									    	              				'used_equipment' => __d('front', 'Equipamento usado'),
									    	              				'mobile_cranes' => __d('front', 'Grúas mobiles'),
									    	              				'truck_cranes' => __d('front', 'Grúas hidráulicas camión'),
									    	              				'terrain_cranes' => __d('front', 'Grúas RT'),
									    	              				'crawler_cranes' => __d('front', 'Grúas oruga'),
									    	              				'tower_cranes' => __d('front', 'Grúas torre'),
									    	              				'boom_trucks' => __d('front', 'Grúas tipo stinger/plataforma'),
									    	              				'hydraulic_gantries' => __d('front', 'Grúas hidráulicas de pórtico'),
									    	              				'dockside' => __d('front', 'Grúas muelle'),
									    	              				'special_transport' => __d('front', 'Transporte especializado'),
									    	              				'telehandlers' => __d('front', 'Telehandlers'),
									    	              				'safety_rtaining' => __d('front', 'Certificación/capacitación'),
									    	              				'ringging_hardware' => __d('front', 'Equipamento para Izaje'),
									    	              				'crane_components' => __d('front', 'Componentes'),


									    	              				//equipamento nuevo o usado
									    	              				'equipment_buy_status' => __d('front', '¿Su empresa compra equipamiento Nuevo o Usado?'),
									    	              				'new_equipment' => __d('front', 'Equipo nuevo'),
									    	              				'used_equipment' => __d('front', 'Equipo usado'),
									    	              				'dont_buy_equipment' => __d('front', 'No compramos equipamento'),

									    	              				//referencia comercial
									    	              				'comercial_ref' => __d('front', 'Referencia comercial'),

									    	              				'paypal_pay' => __d('front', 'Adquiere tu plan'),
									    	              				'get_premium' => __d('front', 'Plan premium plataforma NEXTCRANE') ,
									    	              				'get_premium_6_months' => __d('front', 'Plan premium plataforma NEXTCRANE 6 Meses') ,
									    	              				'pay_status' => __d('front', 'Estado de su transacción'),
									    	              				'transaction' => __d('front', 'Transacción'),
									    	              				'payment_status' => __d('front', 'Estado'),
									    	              				'payment_date' => __d('front', 'Fecha de la transacción'),
									    	              				'payment_gross' => __d('front', 'Valor'),
									    	              				'mc_currency' => __d('front', 'Moneda'),
									    	              				'txn_id' => __d('front', 'Referencia'),
									    	              				'item_name' => __d('front', 'Plan adquirido'),
									    	              				'date_start_plan' => __d('front', 'Inicio del plan'),
									    	              				'date_end_plan' => __d('front', 'Terminación del plan'),
									    	              				'plan' => __d('front', 'Tipo de plan'),
									    	              				'user_name' => __d('front', 'Nombre del usuario'),
									    	              				'user_info' =>  __d('front', 'Información del usuario'),



											    	              		//filtros de busquedas
				    	       											'filter' => __d('front', 'Filtrar por'),	    	       											
				    	       											'search_crane' => __d('front', 'Buscar grúa'),	    	       											
				    	       											'search_parts' => __d('front', 'Buscar partes'),	    	       											
				    	       											'for_sell' => __d('front', 'Para la venta'),	    	       											
				    	       											'for_rent' => __d('front', 'Para la renta'),	    
				    	       											'to_sell' => __d('front', 'Venta'),	    
				    	       											'to_rent' => __d('front', 'Alquiler'),	    
				    	       											'click_to_offer' => __d('front', 'Oferta en USD, Presiona Enter para hacer tu oferta'),	       											
				    	       											'sell' => __d('front', 'Ofertar'),	    	       											
				    	       											'rent' => __d('front', 'Rentar'),	    	       											
				    	       											'type' => __d('front', 'Tipo'),	    	       											
				    	       											'brand' => __d('front', 'Fabricante'),	    	       											
				    	       											'motor' => __d('front', 'Motor'),	    	       											
				    	       											'model' => __d('front', 'Modelo'),	    	       											
				    	       											'city' => __d('front', 'Ciudad'),	  
				    	       											'state' => __d('front', 'Estado/Provincia'),
				    	       											'promotion' => __d('front', 'Promoción'),
				    	       											'continent' => __d('front', 'Continente'),	  
				    	       											'postal_code' => __d('front', 'Código postal'),
				    	       											'send_to_all_companies' => __d('front', 'Por favor envíar esta solicitud a otras empresas de alquiler relacionadas.'),
				    	       											'relationship_cranes' => __d('front', 'Grúas relacionadas'),
				    	       											'relationships' => __d('front', 'Relacionados'),
				    	       											'term' => __d('front', 'Acepto términos y condiciones'),	    	       											
				    	       											'country' => __d('front', 'País'),	    	       											
				    	       											'country_form' => __d('front', 'País'),	    	       											
				    	       											'price' => __d('front', 'Precio'),
				    	       											'1_avalible' => __d('front', 'Vendida'),
				    	       											'2_avalible' => __d('front', 'Alquilada'),	    	       											
				    	       											'3_avalible' => __d('front', 'En negociación'),	    	       											
				    	       											'price_month' => __d('front', 'Mes'),	    	       											
				    	       											'price_year' => __d('front', 'Año'),	    	       											
				    	       											'price_day' => __d('front', 'Día'),	    	       											
				    	       											'price_week' => __d('front', 'Semana'),	    	       											
				    	       											'price_before' => __d('front', 'Precio anterior'),	    	       											
				    	       											'n_a' => __d('front', 'N/A'),	 
				    	       											'get_it_now' => __d('front', 'Adquierelo ahora'),   	       											
				    	       											'since' => __d('front', 'Desde'),
				    	       											'until' => __d('front', 'Hasta'),
				    	       											'cabin' => __d('front', 'Cabina'),
				    	       											'miles' => __d('front', 'Millas'),
				    	       											'hours' => __d('front', 'Horas'),
				    	       											'counterweight' => __d('front', 'Contrapeso'),
				    	       											'transmission' => __d('front', 'Transmisión'),
				    	       											'condition' => __d('front', 'Condición'),
				    	       											'block' => __d('front', 'Blqoue'),
				    	       											'boom' => __d('front', 'Boom'),
				    	       											'jin' => __d('front', 'Jib'),
				    	       											'capacity' => __d('front', 'Capacidad'),
				    	       											'featured' => __d('front', 'Destacados'),
				    	       											'owner' => __d('front', 'Propietario'),
				    	       											'date_publish' => __d('front', 'Fecha de publicación'),
				    	       											'ranking' => __d('front', 'Puntuación'),
				    	       											'location' => __d('front', 'Ubicación'),
				    	       											'reset' => __d('front', 'Limpiar'),
											    	              		'you_are_in' => __d('front', 'Estas en'),	 
											    	              		'you_are_in_profile' => __d('front', 'Estas en el perfil'),	 
											    	              		'write_valid_value' => __d('front', 'Ingresa un valor numérico válido'),	 
											    	              		'min_offer' => __d('front', 'La oferta mínima es'),	 
											    	              		'comments' => __d('front', 'Dudas, sugerencias, comentarios'),								    	              		
											    	              		'email' => __d('front', 'E-mail'),								    	              		
											    	              		'name' => __d('front', 'Nombre'),
											    	              		'last_name' => __d('front', 'Apellidos'),
											    	              		'identification' => __d('front', 'Identificación'),
											    	              		'select_default' => __d('front', 'Seleccióna una opción'),
											    	              		'address' => __d('front', 'Dirección'),
											    	              		'city' => __d('front', 'Ciudad'),
											    	              		'city_form' => __d('front', 'Ciudad'),
											    	              		'country' => __d('front', 'País'),
											    	              		'phone' => __d('front', 'Teléfono'),
											    	              		'tel' => __d('front', 'Teléfono'),
											    	              		'celphone' => __d('front', 'Celular'),
											    	              		'indicative' => __d('front', 'Indicativo'),
											    	              		'indicative_country' => __d('front', 'Indicativo país'),
											    	              		'area_phone' => __d('front', 'Código área'),
											    	              		'area_cel' => __d('front', 'Código área'),
											    	              		'area' => __d('front', 'Área'),
											    	              		'cel' => __d('front', 'Celular'),
											    	              		'password_confirmation' => __d('front', 'Repite contraseña'),
											    	              		'password' => __d('front', 'Contraseña'),
											    	              		'create' => __d('front', 'Crear'),
											    	              		'login' => __d('front', 'Ingresar'),
											    	              		'write_email' => __d('front', 'Digita un correo electrónico válido'),
											    	              		'logout' => __d('front', 'Salir'), 
											    	              		'company_responsible' => __d('front', 'Empresa/Responsable'),
											    	              		'company_name' => __d('front', 'Empresa'),
											    	              		'company_address' => __d('front', 'Dirección de la empresa'),
											    	              		'company_email' => __d('front', 'E-mail empresarial'),
											    	              		'company_tel' => __d('front', 'Teléfono'),
											    	              		'company_city' => __d('front', 'Ciudad'),  
											    	              		'company_country' => __d('front', 'País'),  
											    	              		'company_position' => __d('front', 'Cargo'),
											    	              		'zip_code' => __d('front', 'Código postal'),
											    	              		'company_sector' => __d('front', 'Sector empresarial'),	       											
											    	              		'send' => __d('front', 'Enviar mensaje'),	       											
											    	              		'image' => __d('front', 'Imagen'),
											    	              		'tokenUrl' => __d('front', 'URL para ingresar'),	       
											    	              		'send_email' => __d('front', 'Enviar'),											
											    	              		'actions' => __d('front', 'Acciones'),	       											
				    	       											
				    	       											//horizontal filter
				    	       											'original_order' => __d('front', 'Orden original'),
				    	       											'best_price' => __d('front', 'Mejor precio'),
				    	       											'ref' => __d('front', 'Referencia'),
				    	       											'tons' => __d('front', 'Capacidad'),
				    	       											'tons_alert' => __d('front', 'El valor mínimo es mayor que el máximo en toneladas'),
				    	       											'year_alert' => __d('front', 'El valor mínimo es mayor que el máximo en Años'),
				    	       											'year' => __d('front', 'Año'),
				    	       											'year_maker' => __d('front', 'Año'),
				    	       											'maker' => __d('front', 'Fabricante'),
				    	       											'recent' => __d('front', 'Reciente'),
				    	       											'results_search' => __d('front', 'Estos son los resultados de tu busqueda'),
				    	       											'wrhite_your_search' => __d('front', '¿Qué estas buscando?'),
				    	       											'search' => __d('front', 'Buscar'),


				    	       											// paginador
				    	       											'prev' => __d('front', 'Anterior'),
											    	              		'next' => __d('front', 'Siguiente'),
											    	              		'page' => __d('front', 'Página'),
											    	              		'of' => __d('front', 'de'),
											    	              		'showing' => __d('front', 'mostrando'),
											    	              		'log' => __d('front', 'registro de'),

											    	              		//nuevos arribos
											    	              		'new_arrivals' => __d('front', 'Nuevos arribos'),
											    	              		'see_map' => __d('front', 'Ver/Ocultar mapa'),
											    	              		'contact_owner' => __d('front', 'Contactar al propietario'),
											    	              		'see_owner_site' => __d('front', 'Micrositio del propietario'),
											    	              		'contact_company' => __d('front', 'Ampliar información'),
											    	              		'save_favorite' => __d('front', 'Guardar en favoritos'),
											    	              		'remove_favorite' => __d('front', 'Quitar de favoritos'),
											    	              		'see_contact' => __d('front', 'Ver datos de contacto'),
											    	              		'alert_email' => __d('front', 'Email de alerta'),
											    	              		'quote' => __d('front', 'Imprimir cotización'),
											    	              		'quote_title' => __d('front', 'Cotización'),
											    	              		'shared' => __d('front', 'Compartir grúa'),
											    	              		'post_crane' => __d('front', 'Publicar grúa'),
											    	              		
											    	              		//
											    	              		'publicated' => __d('front', 'Publicado'),
											    	              		'modified' => __d('front', 'ültima actualización'),
											    	              		'technical_specifications' => __d('front', 'Especificaciones técnicas'),
											    	              		'crane_structure' => __d('front', 'Estructura grúa'),
											    	              		'truck_structure' => __d('front', 'Estructura camión'),
											    	              		'prices' => __d('front', 'Precios'),
											    	              		'other' => __d('front', 'Otros'),
											    	              		'details' => __d('front', 'Especificaciones'),
											    	              		'see_more_details' => __d('front', 'Ver más detalles'),
											    	              		'sub_items' => __d('front', 'Sub elementos'),
											    	              		'latests_publications' => __d('front', 'Últimas grúas'),
											    	              		'cranes' => __d('front', 'Grúas'),
											    	              		'crane_serial' => __d('front', 'Serial de la grúa'),
											    	              		'date_rent' => __d('front', 'Fecha de la solicitud para la renta'),
											    	              		'date_sell' => __d('front', 'Fecha de la solicitud para la venta'),
											    	              		'crane_manual' => __d('front', 'Manual de la grúa'),
											    	              		'published_cranes' => __d('front', 'Grúas publicadas'),

											    	              		//facebook login
											    	              		'facebook_singin' => __d('front', 'Regístrate con Facebook'),
											    	              		'facebook_login' => __d('front', 'Inicia sesión con Facebook'),
											    	              		'facebook_login_description' => __d('front', 'No publicaremos nada sin tu permiso'),
											    	              		'complete_form' => __d('front', 'Completa el siguiente formulario'),
											    	              		'start_session' => __d('front', 'Ingresa los datos e inicia sesión'),
											    	              		'password' => __d('front', 'Contraseña'),
											    	              		'password_confirm' => __d('front', 'Confirmar contraseña'),
											    	              		'update_password' => __d('front', 'Actualizar contraseña'),
											    	              		'update' => __d('front', 'Actualizar información'),
											    	              		'update_term' => __d('front', 'Continuar'),
											    	              		'update_bussines_user' => __d('front', 'Cambiar a empresarial'),
											    	              		'accept_terms' => __d('front', 'Acepto los Términos y condiciones'),

											    	              		//profile
											    	              		'total_publications' => __d('front', 'Total publicaciones'),
											    	              		'general_data' => __d('front', 'Información personal'),
											    	              		'general_data_term' => __d('front', 'Antes de continuar actualiza tus datos'),
											    	              		'company_data' => __d('front', 'Datos de la empresa'),
											    	              		'company_profile' => __d('front', 'Perfil empresarial'),
											    	              		'company_update' => __d('front', 'Actualizar empresa'),
											    	              		'contact_information' => __d('front', 'Información de contacto'),
											    	              		'password_stronger' => __d('front', 'Contraseña muy segura'),
											    	              		'password_strong' => __d('front', 'Contraseña segura, agrega algún caracter para que sea más segura'),
											    	              		'password_good' => __d('front', 'Contraseña media, agrega números y caracteres para que sea más segura'),
											    	              		'password_weak' => __d('front', 'Contraseña débil, intenta alguna contraseña más segura'),
											    	              		'password_weaker' => __d('front', 'Contraseña muy débil, cambiala por seguridad'),
											    	              		'password_dont_match' => __d('front', 'Las contraseñas no concuerdan'),
											    	              		'password_match' => __d('front', 'Las contraseñas concuerdan'),
											    	              		'user_data' => __d('front', 'Datos del propietario'),
		  
											    	              		//site
											    	              		'welcome' => __d('front', 'Bienvenido'),
											    	              		'see_site' => __d('front', 'Revisa tu sitio'),
											    	              		'my_favorites' => __d('front', 'Mis Favoritos'),
											    	              		'my_favorites_description' => __d('front', 'Estas son todas las grúas que tienes guardadas en favoritos'),
											    	              		'update_info' => __d('front', 'Actualizar datos'),
											    	              		'login_to_see_more' => __d('front', 'Ingresa para más información'),

											    	              		//buscador
											    	              		'cities_codes' => __d('front', 'Ciudad / Código postal'),
											    	              		'country' => __d('front', 'Pais'),


				    	       								        ),

				    			'Images' => 				  array(   	'title' =>   __d('front', 'Imágenes para esta publicación'),
											    	              		'label' =>    __d('front', 'Imagen Destacada'),
											    	              		'description' => __d('front', ''),
											    	              		'featured_picture' => __d('front', 'Imagen destacada'),
											    	              		'see_all_files' => __d('front', 'Ver todos los archivos'),
											    	              		'gallery_title' => __d('front', 'Galería de imágenes'),
											    	              		'gallery_description' => __d('front', 'Seleccióna las imágenes que quieres que aparezcan en tu galería, si el tema lo soporta, estas aparecerán en tu sitio.'),
											    	              		'gallery_featured_description' => __d('front', 'Seleccióna la imagen destacada para esta publicación.'),
											    	              		'upload_text' => __d('front', 'Arrastra la imagen destacada hasta aquí'),
											    	              		'select_images' => __d('front', 'Seleccióna'),
											    	              		'remove_image' => __d('front', 'Quitar imagen destacada'),
											    	              		'button'=>__d('front', 'Agregar Imagenes'),
											    	              		'button_profile'=>__d('front', 'Logo personal o empresarial'),
											    	              		'submit_thumbnail'=>__d('front', 'Actualizar imagen destacada'),
											    	              		'submit_gallery'=>__d('front', 'Actualizar galería'),
											    	              		'update_logo' => __d('front', 'Cambiar logo'),


				    	       								        ),
				    									
								

								// Fontpage
				    	       'Front' => array('index' =>      array(	'crane_publish' => __d('front', 'Publica tu grua'),	    	       											

				    	                        					),

				    	       				),

				    	       'Search' => array('index' =>       array('title' => __d('front', 'Estos son los resultados de tu busqueda'),
				    	       											'description' => __d('front', ''),
				    	       					),

				    	       					'simple_search' => array('title' => __d('front', 'Estos son los resultados de tu busqueda'),
				    	       											'description' => __d('front', ''),

				    	                        					),

				    	       				),


				    	       // Categorias
				    	       'Categories' => array('index' => array(	
				    	                        					),

				    	       				),

			    	       			    
				    	    						
				    	 );


					$text = $espanol;

			

		  return @array($controlador => $text[$controlador][$vista], 'Extras' => $text['Extras'], 'Images' => $text['Images']);

    }


}

?>