<?php
/*
variables de texto para las vistas
*/
namespace Administrator\Controller\Component;

use Cake\Controller\Component;


class TextsComponent extends Component {

	    public function text ($controlador, $vista) {
		    	
		$text = 
		    	array(	

		    			'Extras' => 				  array(   	'created' => __d('administrator', 'Creado'),
									    	              		'modified' => __d('administrator', 'Modificado'),
									    	              		'status' => __d('administrator', 'Estado'),
									    	              		'trash' => __d('administrator', 'Papelera'),
									    	              		'move_trash' => __d('administrator', 'Mover a papelera'),
									    	              		'desactive_user' => __d('administrator', 'Desactivar usuario'),
									    	              		'view' => __d('administrator', 'Ver en la web'),
									    	              		'update' => __d('administrator', 'Actualizar'),
									    	              		'add' => __d('administrator', 'Añadir nuevo'),
									    	              		'publish' => __d('administrator', 'Publicar'),
									    	              		'edit' => __d('administrator', 'Editar'),
									    	              		'delete' => __d('administrator', 'Eliminar'),
									    	              		'restore' => __d('administrator', 'Restaurar'),
									    	              		'move_trash' => __d('administrator', 'Mover a papelera'),
									    	              		'actions' => __d('administrator', 'Acciones'),
									    	              		'date_created' => __d('administrator', 'Fecha de creación'),
									    	              		'date_modified' => __d('administrator', 'Fecha de modificación'),
									    	              		'image' => __d('administrator', 'Imagen'),
									    	              		'title' => __d('administrator', 'Título'),
									    	              		'description' => __d('administrator', 'Descripción'),
									    	              		'url' => __d('administrator', 'URL'),
									    	              		'code' => __d('administrator', 'SC'),
									    	              		'get_premium_now' => __d('administrator', 'Texto planes (perfil usuario)'),
									    	              		'button_text' => __d('administrator', 'Texto del boton'),
									    	              		'email' => __d('administrator', 'Correo electrónico'),								    	              		
									    	              		'noreply' => __d('administrator', 'Correo automático'),								    	              		
									    	              		'name' => __d('administrator', 'Nombre'),
									    	              		'premium' => __d('administrator', 'Premium plan USD'),
									    	              		'professional_plan' => __d('administrator', 'Professional plan USD'),
									    	              		'banner_rotative' => __d('administrator', 'Valor banner Premium rotativo USD'),
									    	              		'banner_premium' => __d('administrator', 'Valor banner + video USD'),
									    	              		'banner_static' => __d('administrator', 'Valor banner estático USD'),
									    	              		'banner_rotetive_internal' => __d('administrator', 'Valor banner interno USD'),
									    	              		'banner_rotative_logotype_home' => __d('administrator', 'Valor banner + logotipo inicio USD'),
									    	              		'last_name' => __d('administrator', 'Apellidos'),
									    	              		'identification' => __d('administrator', 'Identificación'),
									    	              		'details_alert' => __d('front', 'Importante: Una grúa de tu interés ha sido modificada recientemente, Ingresa al siguiente link para conocer más detalles.'),
									    	              		'select_default' => __d('administrator', 'Selecciona una opción'),
									    	              		'address' => __d('administrator', 'Dirección'),
									    	              		'city' => __d('administrator', 'Ciudad'),
									    	              		'state' => __d('administrator', 'Estado/Provincia'),
									    	              		'company_state' => __d('administrator', 'Estado/Provincia'),
									    	              		'loading' => __d('administrator', 'Cargando'),
									    	              		'loading_cities' => __d('administrator', 'Cargando...'),
									    	              		'without_title' => __d('administrator', 'sin título'),
									    	              		'country' => __d('administrator', 'País'),
									    	              		'sell' => __d('administrator', 'VENTA'),
									    	              		'rent' => __d('administrator', 'ALQUILER'),
									    	              		'new_tab' => __d('administrator', 'Nueva ventana'),
									    	              		'duplicated_crane' => __d('administrator', 'Duplicar para la venta'),
									    	              		'phone' => __d('administrator', 'Teléfono'),
									    	              		'celphone' => __d('administrator', 'Celular'),								    	              		
									    	              		'licence' => __d('administrator', 'Licencia'),								    	              		
									    	              		'Caducidad' => __d('administrator', 'Caducidad'),								    	              		
									    	              		'thumbnail_size' => __d('administrator', 'Tamaño de la miniatura (px)'),								    	              		
									    	              		'logo' => __d('administrator', 'Logo de la empresa'),								    	              		
									    	              		'favicon' => __d('administrator', 'Icono principal'),								    	              		
									    	              		'pbx' => __d('administrator', 'PBX'),
									    	              		'rol' => __d('administrator', 'Tipo de usuario'),									    	              		
									    	              		'suscribe' => __d('administrator', 'Suscríbete'),
									    	              		'suscribe_description' => __d('administrator', 'Suscríbete a nuestras promociones'),
									    	              		'send' => __d('administrator', 'Enviar'),
									    	              		'read_more' => __d('administrator', 'Leer más'),
									    	              		'see_more' => __d('administrator', 'Ver más'),
									    	              		'prev' => __d('administrator', 'Anterior'),
									    	              		'next' => __d('administrator', 'Siguiente'),
									    	              		'page' => __d('administrator', 'Página'),
									    	              		'of' => __d('administrator', 'de'),
									    	              		'indicative' => __d('administrator', 'Indicativo'),
									    	              		'code_area' => __d('administrator', 'Código de área'),
									    	              		'author' => __d('administrator', 'Autor'),
									    	              		'actual_language' => __d('administrator', 'Lenguaje actual'),
									    	              		'en' => __d('administrator', 'Inglés'),
									    	              		'es' => __d('administrator', 'Español'),
									    	              		'pt' => __d('administrator', 'Portugues'),

									    	              		//tipo de industria
									    	              		'industry_type' => __d('administrator', 'Tipo de industria a la que pertenece'),
									    	              		'industry_type_label' => __d('administrator', 'Tipo de industria'),
									    	              		'contractor' => __d('administrator', 'Contratista, Construcción'),
									    	              		'rental_heavy_equipment' => __d('administrator', 'Alquiler grúas y maquinaria pesada'),
									    	              		'special_transportation' => __d('administrator', 'Transporte especializado'),
									    	              		'utility_mining_oil' => __d('administrator', 'Servicios mineria oil & gas'),
									    	              		'new_distrbuitor_parts' => __d('administrator', 'Distribuidor maquinaria nueva'),
									    	              		'used_distrbuitor_broker' => __d('administrator', 'Distribuidor Maquinaria Usada'),
									    	              		'windowpower' => __d('administrator', 'Energia eólica'),
									    	              		'manufacturer' => __d('administrator', 'Fabricante de equipos de pesaje y transporte'),
									    	              		'server_repair' => __d('administrator', 'Servicio técnico de grúas'),
									    	              		'certification_company' => __d('administrator', 'Empresa certificadora & asociaciones'),
									    	              		'others' => __d('administrator', 'Otros'),

									    	              		//tipo de equipamento
									    	              		'equipment_type' => __d('administrator', '¿Qué tipo de equipo compra, usa o vende?'),
									    	              		'equipment_new' => __d('administrator', 'Equipamento nuevo'),
									    	              		'dont_buy_equipment' => __d('administrator', 'No compro equipamento'),
									    	              		'used_equipment' => __d('administrator', 'Equipamento usado'),
									    	              		'mobile_cranes' => __d('administrator', 'Grúas mobiles'),
									    	              		'truck_cranes' => __d('administrator', 'Grúas hidráulicas camión'),
									    	              		'terrain_cranes' => __d('administrator', 'Grúas RT'),
									    	              		'crawler_cranes' => __d('administrator', 'Grúas oruga'),
									    	              		'tower_cranes' => __d('administrator', 'Grúas torre'),
									    	              		'boom_trucks' => __d('administrator', 'Grúas tipo stinger/plataforma'),
									    	              		'hydraulic_gantries' => __d('administrator', 'Grúas hidráulicas de pórtico'),
									    	              		'dockside' => __d('administrator', 'Grúas muelle'),
									    	              		'special_transport' => __d('administrator', 'Transporte especializado'),
									    	              		'telehandlers' => __d('administrator', 'Telehandlers'),
									    	              		'safety_rtaining' => __d('administrator', 'Certificación/capacitación'),
									    	              		'ringging_hardware' => __d('administrator', 'Equipamento para Izaje'),
									    	              		'crane_components' => __d('administrator', 'Componentes'),									    	              		

									    	              				//equipamento nuevo o usado
									    	              		'equipment_buy_status' => __d('front', '¿Su empresa compra equipamiento Nuevo o Usado?'),
									    	              		'new_equipment' => __d('front', 'Equipo nuevo'),
									    	              		'used_equipment' => __d('front', 'Equipo usado'),
									    	              		'dont_buy_equipment' => __d('front', 'No compramos equipamento'),


									    	              		'showing' => __d('administrator', 'mostrando'),
									    	              		'log' => __d('administrator', 'registro de'),
									    	              		'password' => __d('administrator', 'contraseña'),
									    	              		'confirm_password' => __d('administrator', 'Repite la contrañeña'),
									    	              		'password_description' => __d('administrator', 'Genera una contraseña y confirmala para poder continuar.'),
									    	              		'forgot_password' => __d('administrator', '¿Olvidó su contraseña?'),
									    	              		'author' => __d('administrator', 'Autor'),
									    	              		'contact' => __d('administrator', 'Contacto'),
									    	              		'value' => __d('administrator', 'Valor'),
											    	            'counteroffer' => __d('administrator', 'Contraoferta'),
											    	            'crane_author' => __d('administrator', 'Solicitante'),
											    	            'crane_status' => __d('administrator', 'Disponibilidad'),
									    	              		'since' => __d('administrator', 'Desde'),
									    	              		'form' => __d('administrator', 'Formulario de contacto'),
									    	              		'form_description' => __d('administrator', 'Estos son los campos que aparecerán en el formulario'),								    	              		
									    	              		'shared' => __d('administrator', 'Compartir en'),
									    	              		'navigate_keyboard' => __d('administrator', 'Navega con el teclado'),
									    	              		'gadget' => __d('administrator', 'Gadget para esta página'),
									    	              		'send_message' => __d('administrator', 'El mensaje se ha enviado correctamente.'),
									    	              		'error_message' => __d('administrator', 'El mensaje no se ha enviado, intentalo de nuevo.'),
									    	              		'posts' => __d('administrator', 'Publicaciones'),
									    	              		'post' => __d('administrator', 'Publicación'),
									    	              		'pages' => __d('administrator', 'Páginas'),
									    	              		'page' => __d('administrator', 'Página'),
									    	              		'category' => __d('administrator', 'Categoría'),
									    	              		'categories' => __d('administrator', 'Categorias'),								    	              		
									    	              		'gadgets' => __d('administrator', 'Gadgets'),								    	              		
									    	              		'gadget' => __d('administrator', 'Gadget'),								    	              		
									    	              		'archives' => __d('administrator', 'Archivos'),
									    	              		'archive' => __d('administrator', 'Archivo'),
									    	              		'gallery' => __d('administrator', 'Media'),
									    	              		'new_custom' => __d('administrator', 'Nuevo campo personalizado'),
									    	              		'description_new_custom' => __d('administrator', 'Genera nuevos campos adicionales de ser necesario, si el frontend lo soporta estos aparecerán en el sitio.'),
									    	              		'confirm_restore_user' => __d('administrator', 'El usuario se activará'),
									    	              		'confirm_trash_user' => __d('administrator', 'El usuario se inhabilitará'),
									    	              		'confirm_delete_user' => __d('administrator', 'El usuario se eliminará por completo del sistema'),
									    	              		'you_are_in' => __d('administrator', 'Estas en'),
									    	              		'suscribe_info' => __d('administrator', 'Texto Suscríbete'),
									    	              		'contact_info' => __d('administrator', 'Texto contáctenos'),
									    	              		'slug' => __d('administrator', 'Link amigable'),
									    	              		'frontend_main' => __d('administrator', 'Menú principal'),
									    	              		'main_about_us' => __d('administrator', 'Menú Nosotros'),
									    	              		'main_services' => __d('administrator', 'Menú servicios'),
									    	              		'main_members' => __d('administrator', 'Menú Miembros'),

									    	              		//controladores

									    	              		'restricted_area' =>  __d('administrator', 'Area de acceso restringida.'),

									    	              		//archives
									    	              		'flash_delete_archives' => __d('administrator', 'Los archivos multimedia se han eliminado por completo'),
									    	              		'flash_delete_archive' => __d('administrator', 'El archivo multimedia se han eliminado por completo'),
									    	              		'flash_update_archive' => __d('administrator', 'Archivo multimedia actualizado'),

									    	              		//catgorias
									    	              		'category_papercut' => __d('administrator', 'Categoría enviada a papelera'),
									    	              		'category_dont_remove' => __d('administrator', 'Lo sentimos, esta categoría no se puede eliminar'),
									    	              		'category_updated' => __d('administrator', 'Categoría actualizada correctamente'),
									    	              		'category_created' => __d('administrator', 'Categoría creada'),
									    	              		'category_deleted' => __d('administrator', 'Categoría eliminada'),
									    	              		'this_category_dont_remove' => __d('administrator', 'Lo sentimos, ésta categoría no se puede eliminar'),
									    	              		'category_restored' => __d('administrator', 'Categoría restaurada correctamente'),
 

									    	              		//fields location
											    	            'technical_specifications' => __d('administrator', 'Especificaciones técnicas'),
											    	            'crane_structure' => __d('administrator', 'Estructura grúa'),
											    	            'truck_structure' => __d('administrator', 'Estructura camión'),
											    	            'other' => __d('administrator', 'Otros'),

											    	            //disponiblidad
											    	            'avalible_crane' => __d('administrator', 'Disponible'),
											    	            'sold' => __d('administrator', 'Vendida'),
											    	            'rented' => __d('administrator', 'Alquilada'),	    	              		
											    	            'pending' => __d('administrator', 'En negociación'),	    	              		

									    	              		//Buscador
											   	             	'search'=> __d('administrator', 'Buscar'),
											   	             	'origin_city'=> __d('administrator', 'Ciudad de Viaje'),
											   	             	'hotel'=> __d('administrator', 'Hotel'),
											   	             	'fechaIn'=> __d('administrator', 'Fecha de Entrada'),
											   	             	'fechaOut'=> __d('administrator', 'Fecha de Salida'),
											   	             	'hab'=> __d('administrator', 'N° de Habitaciones'),
											   	             	'adult'=> __d('administrator', 'Adulto'),
											   	             	'children'=> __d('administrator', 'Niño'),
											   	             	'reserved'=> __d('administrator', 'Reservar'),
											   	             	'avalible' => __d('administrator', 'Disponible para'),
											   	             	'offer_date' => __d('administrator', 'Fecha de la oferta'),
											   	             	'id' => __d('administrator', 'ID'),
											   	             	'weight' => __d('administrator', 'Peso'),
											   	             	'maker' => __d('administrator', 'Fabricante'),
											   	             	'capacity' => __d('administrator', 'Capacidad'),

											   	             	//index
											   	             	'all_selection' => __d('administrator', 'Para todos los elementos seleccionados'),
											   	             	'actions' => __d('administrator', 'Acciones'),
									    	              		'Users' => __d('administrator', 'usuarios'),
									    	              		'Users' => __d('administrator', 'usuarios'),
									    	              		'Categories' => __d('administrator', 'categorías'),
									    	              		'Posts' => __d('administrator', 'publicaciones'),
									    	              		'Pages' => __d('administrator', 'páginas'),
									    	              		'Gadgets' => __d('administrator', 'gadgets'),
									    	              		'SellRent' => __d('administrator', 'Ofertas'),
									    	              		'Payments' => __d('administrator', 'Transacciones'),
									    	              		'confirm_delete_image_gadget' => __d('administrator', '¿Desea eliminar esta imagen?'),
									    	              		'Archives' => __d('administrator', 'archivos multimedia'),
									    	              		'Search' => __d('administrator', 'Buscador'),
									    	              		'Generals' => __d('administrator', 'generales'),
									    	              		'table_created' => __d('administrator', 'Fecha de creación'),
									    	              		'table_modified' => __d('administrator', 'Fecha de modificación'),									    	              		
									    	              		'table_id' => __d('administrator', 'ID'),	
									    	              		'banner_home' => __d('administrator', 'Banner inicio'),								    	              		
									    	              		'publicity_home' => __d('administrator', 'Publicidad inicio'),								    	              		
									    	              		'publicity_up' => __d('administrator', 'Publicidad superior (Páginas)'),								    	              		
									    	              		'publicity_user' => __d('administrator', 'Publicidad interna (Usuario)'),								    	              		
									    	              		'video' => __d('administrator', 'Video'),								    	              		
									    	              		'background' => __d('administrator', 'Fondo administrable'),								    	              		

									    	              		//profile
									    	              		'total_publications' => __d('administrator', 'Total publicaciones'),
									    	              		'general_data' => __d('administrator', 'Datos generales'),
									    	              		'contact_information' => __d('administrator', 'Información de contacto'),
									    	              		'company_data' => __d('administrator', 'Información de la empresa'),
									    	              		'company_name' => __d('administrator', 'Nombre (Razón social)'),
									    	              		'company_email' => __d('administrator', 'Email empresa'),
									    	              		'company_city' => __d('administrator', 'Ciudad empresa'),
									    	              		'company_address' => __d('administrator', 'Dirección empresa'),
									    	              		'company_country' => __d('administrator', 'País empresa'),
									    	              		'company_tel' => __d('administrator', 'PBX empresa'),
									    	              		'company_identification' => __d('administrator', 'Nit'),
									    	              		'company_position' => __d('administrator', 'Cargo'),
									    	              		'password_stronger' => __d('administrator', 'Contraseña muy segura'),
									    	              		'password_strong' => __d('administrator', 'Contraseña segura, agrega algún caracter para que sea más segura'),
									    	              		'password_good' => __d('administrator', 'Contraseña media, agrega números y caracteres para que sea más segura'),
									    	              		'password_weak' => __d('administrator', 'Contraseña débil, intenta alguna contraseña más segura'),
									    	              		'password_weaker' => __d('administrator', 'Contraseña muy débil, cambiala por seguridad'),
									    	              		'password_dont_match' => __d('administrator', 'Las contraseñas no concuerdan'),
									    	              		'password_match' => __d('administrator', 'Las contraseñas concuerdan'),

									    	              		//edit views
									    	              		'custom_link' => __d('administrator', 'Enlace'),
									    	              		'custom_link_placeholder' => __d('administrator', 'Agrega o cambia el enlace personalizado'),									    	              		
									    	              		'general_description' => __d('administrator', 'Descripción general'),
									    	              		'theme' => __d('administrator', 'Plantilla'),
									    	              		'icon' => __d('administrator', 'Icono'),
									    	              		'placeholder_description' => __d('administrator', 'Agrega una descripción aquí'),
									    	              		'custom_fields' => __d('administrator', 'Campos adicionales'),
									    	              		'location' => __d('administrator', 'Ubicación'),
									    	              		'plan' => __d('administrator', 'Tipo de plan'),
									    	              										    	              		
									    	              		//imagenes
									    	              		'upload_button' => __d('administrator', 'Buscar archivos'),
									    	              		'upload_image' => __d('administrator', 'Agrega los archivos de imagen aquí'),
									    	              		'mimetype' => __d('administrator', 'Formato'),
									    	              		'type' => __d('administrator', 'Tipo'),
									    	              		'filesize' => __d('administrator', 'Tamaño KB'),

									    	              		//colores
									    	              		'restart_colors' => __d('administrator', 'Restaurar colores'),
									    	              		'color0' => __d('administrator', 'Oscuro principal'),
									    	              		'color1' => __d('administrator', 'Textos'),
									    	              		'color2' => __d('administrator', 'Títulos'),
									    	              		'color3' => __d('administrator', 'Enlaces'),
									    	              		'color4' => __d('administrator', 'Adicional'),
									    	              		'color5' => __d('administrator', 'Textos claros'),

									    	              		//gadgets
									    	              		'id' => __d('administrator', 'ID'),
									    	              		'image' => __d('administrator', 'Imagen'),
									    	              		'url' => __d('administrator', 'Enlace'),
									    	              		'customers' => __d('administrator', 'ID de gadget (Clientes)'),

									    	              		//sell rent
									    	              		'alerts_log' => __d('administrator', 'Registro de alertas'),
									    	              		'offer_info' => __d('administrator', 'Datos de la oferta'),
									    	              		'postal_code' => __d('administrator', 'Código postal'),


		    	       								        ),

		    			'Images' => 				  array(   	'title' =>  __d('administrator', 'Imágenes para esta publicación'),
									    	              		'label' =>    __d('administrator', 'Imagen Destacada'),
									    	              		'description' => __d('administrator', ''),
									    	              		'featured_picture' => __d('administrator', 'Imagen destacada'),
									    	              		'see_all_files' => __d('administrator', 'Ver todos los archivos'),
									    	              		'gallery_title' => __d('administrator', 'Galería de imágenes'),
									    	              		'gallery_description' => __d('administrator', 'Selecciona las imágenes que quieres que aparezcan en tu galería, si el tema lo soporta, estas aparecerán en tu sitio.'),
									    	              		'gallery_featured_description' => __d('administrator', 'Selecciona la imagen destacada para esta publicación.'),
									    	              		'upload_text' => __d('administrator', 'Arrastra la imagen destacada hasta aquí'),
									    	              		'select_images' => __d('administrator', 'Selecciona'),
									    	              		'remove_image' => __d('administrator', 'Quitar imagen destacada'),
									    	              		'button'=> __d('administrator', 'Agregar Imagenes'),
									    	              		'submit_thumbnail'=> __d('administrator', 'Actualizar imagen destacada'),
									    	              		'submit_gallery'=> __d('administrator', 'Actualizar galería'),

									    	              		//generals
									    	              		'change_logo' => __d('administrator', 'Cambiar logo'),
									    	              		'change_favicon' => __d('administrator', 'Cambiar Favicon'),
									    	              		'change_background' => __d('administrator', 'Cambiar Fondo'),

									    	              		'select_logo' => __d('administrator', 'Logotipo principal'),
									    	              		'select_logo_description' => __d('administrator', 'Selecciona la imagen que utilizarás como logotipo de tu web'),

									    	              		'select_favicon' => __d('administrator', 'Favicon principal'),
									    	              		'select_favicon_description' => __d('administrator', 'Selecciona la imagen que utilizarás como favicon de tu web'),

									    	              		'select_background' => __d('administrator', 'Fondo principal'),
									    	              		'select_background_description' => __d('administrator', 'Selecciona la imagen que utilizarás como fondo de tu web'),


		    	       								        ),
		    			// gadgets
		    	       'Gadgets' => array('edit' =>   array(	'title' =>   __d('administrator', 'Editar gadget'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega el titulo de tu publicación'),
									    	              		'description' =>  __d('administrator', ''),
									    	              		'excerpt' => __d('administrator', 'Texto destacado'),
									    	              		'submit' => __d('administrator', 'Actualizar gadget'),
		    	                        					),

		    	       					  'add' =>    array(	'title' => __d('administrator', 'Añadir gadget'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega el titulo de tu publicación'),
									    	              		'description' => __d('administrator', ''),
									    	              		'excerpt' => __d('administrator', 'Texto destacado'),
									    	              		'submit' => __d('administrator', 'Generar gadget'),
		    	                        					),

		    	       					  'index' =>  array(	'title' => __d('administrator', 'Gadgets activos'),
									    	              		'description' => __d('administrator', ''),
									    	              		'all' => __d('administrator', 'Todos'),
									    	              		'active' => __d('administrator', 'Activos'),								    	              		
									    	              		'inactive' => __d('administrator', 'Inactivos'),
									    	              		'trash_restore' => __d('administrator', 'Mover a papelera'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_type' => __d('administrator', 'Tipo de gadget'),
									    	              		'table_email' => __d('administrator', 'Correo'),
									    	              		'table_created' => __d('administrator', 'Fecha de creación'),
									    	              		'table_modified' => __d('administrator', 'Fecha de modificación'),
									    	              		'controller' => __d('administrator', 'gadgets'),
		    	                        					),

		    	       					  'trash' =>  array(	'title' => __d('administrator', 'Gadgets inactivos'),
									    	              		'description' => __d('administrator', ''),
									    	              		'all' => __d('administrator', 'Todos'),
									    	              		'active' => __d('administrator', 'Activos'),								    	              		
									    	              		'inactive' => __d('administrator', 'Inactivos'),
									    	              		'trash_restore' => __d('administrator', 'Mover a papelera'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_type' => __d('administrator', 'Tipo de gadget'),
									    	              		'table_email' => __d('administrator', 'Correo'),
									    	              		'table_created' => __d('administrator', 'Fecha de creación'),
									    	              		'table_modified' => __d('administrator', 'Fecha de modificación'),
									    	              		'controller' => __d('administrator', 'gadgets'),
		    	                        					),

		    	       				),
						
						//users
						'Users' => array('edit' =>   array(		'title' => __d('administrator', 'Editar Usuario'),
																'description' => __d('administrator', 'Actualiza la información de tu perfil desde esta sección'),
									    	              		'submit' => __d('administrator', 'Actualizar usuario'),
									    	              		'user_type' => __d('administrator', 'Tipo de usuario'),
									    	              		'empty_passwords' => __d('administrator', '* Si no deseas cambiar la contraseña deja los campos en blanco'),

		    	                        					),

		    	       					  'add' =>    array(	'title' => __d('administrator', 'Generar usuario'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega el título de tu publicación'),
									    	              		'description' => __d('administrator', 'Agrega aquí los datos del nuevo usuario'),
									    	              		'user_type' => __d('administrator', 'Tipo de usuario'),								    	              		
									    	              		'empty_passwords' => __d('administrator', '* Si no deseas cambiar la contraseña deja los campos en blanco'),
									    	              		'submit' => __d('administrator', 'Generar usuario'),
		    	                        					),

		    	       					  'profile'=> array(	'title' => __d('administrator', 'Tu perfil'),
									    	              		'description' => __d('administrator', 'Edita la información de tu perfil de ser necesario.'),
									    	              		'user_type' => __d('administrator', 'Tipo de usuario'),
									    	              		'submit' => __d('administrator', 'Actualizar perfil'),
									    	              		'empty_passwords' => __d('administrator', '* Si no deseas cambiar la contraseña deja los campos en blanco'),
		    	                        					),

		    	       					  'index' =>  array(	'title' => __d('administrator', 'Todos los usuarios'),
									    	              		'description' => __d('administrator', 'Aquí podrás editar, crear o eliminar los usuarios que se encuentran registrados en la web.'),
									    	              		'all' => __d('administrator', 'Todos los usuarios'),
									    	              		'active' => __d('administrator', 'Usuarios activos'),								    	              		
									    	              		'inactive' => __d('administrator', 'Usuarios Inactivos'),
									    	              		'trash_restore' => __d('administrator', 'Mover a papelera'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_type' => __d('administrator', 'Tipo de usuario'),
									    	              		'table_email' => __d('administrator', 'Correo'),
									    	              		'table_created' => __d('administrator', 'Fecha de creación'),
									    	              		'table_modified' => __d('administrator', 'Fecha de modificación'),
									    	              		'controller' => __d('administrator', 'usuarios'),
		    	                        					),

		    	       					  'trash' =>  array(	'title' => __d('administrator', 'Usuarios inactivos'),
									    	              		'description' => __d('administrator', 'Aquí podrás eliminar completamente algún usuario o activarlo nuevamente.'),
									    	              		'all' => __d('administrator', 'Todos los usuarios'),
									    	              		'active' => __d('administrator', 'Usuarios activos'),								    	              		
									    	              		'inactive' => __d('administrator', 'Usuarios Inactivos'),
									    	              		'trash_restore' => __d('administrator', 'Restaurar usuarios'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_type' => __d('administrator', 'Tipo de usuario'),
									    	              		'table_email' => __d('administrator', 'Correo'),
									    	              		'table_created' => __d('administrator', 'Fecha de creación'),
									    	              		'table_modified' => __d('administrator', 'Fecha de modificación'),
									    	              		'controller' => __d('administrator', 'usuarios'),
		    	                        					),

		    	       					  'login' =>  array(	'submit' => __d('administrator', 'Iniciar sesión'),
		    	       					              	    ),


		    	       					  'forgetpwd'=>array(	'submit' => __d('administrator', 'Recuperar contraseña'),
		    	       					              	    ),

		    	       					  'reset'=>    array(	'submit' => __d('administrator', 'Restaurar contraseña'),
		    	       					              	    ),

		    	       				),
						
						//frontend de la web
					   'Payments'=>array('index' =>  array(	'title' => __d('administrator', 'Todas las transacciones'),
									    	              		'description' => __d('administrator', 'Aquí podrás visualizar las transacciones realizadas en la web.'),
									    	              		'all' => __d('administrator', 'Todos los pagos'),
									    	              		'active' => __d('administrator', 'Pagos actuales'),								    	              		
									    	              		'inactive' => __d('administrator', 'Pagos anteriores'),
									    	              		'trash_restore' => __d('administrator', 'ocultar transacciones'),
									    	              		'table_name' => __d('administrator', 'Usuario'),
									    	              		'table_item_name' => __d('administrator', 'Plan adquirido'),
									    	              		'table_type' => __d('administrator', 'Tipo de usuario'),
									    	              		'table_payment_status' => __d('administrator', 'Estado del pago'),
									    	              		'table_payment_gross' => __d('administrator', 'Valor cancelado'),
									    	              		'table_txn_id' => __d('administrator', 'Ref transacción'),
									    	              		'table_plan' => __d('administrator', 'Plan adquirido'),
									    	              		'table_created' => __d('administrator', 'Fecha de creación'),
									    	              		'table_modified' => __d('administrator', 'Fecha de modificación'),
									    	              		'controller' => __d('administrator', 'usuarios'),
									    	        ),
									),


						// generals
		    	       'Generals' => array('index' =>   array(	'title' => __d('administrator', 'Ajustes generales'),
									    	              		'description' => __d('administrator', 'Estos son los ajustes principales de tu web'),
									    	              		'main_fields' => __d('administrator', 'Campos principales'),
		    	       											'custom_colors' => __d('administrator', 'Personalización de colores'),
		    	       											'routes' => __d('administrator', 'Enlaces personalizados'),							    	              		
									    	              		'submit' => __d('administrator', 'Actualizar'),
		    	                        					),

		    	       					  'appearance' =>array(	'title' => __d('administrator', 'Apariencia del sitio'),
									    	              		'description' => __d('administrator', 'Estos son los ajustes para el tema en tu website'),
									    	              		'main_fields' => __d('administrator', 'Campos principales'),
		    	       											'custom_colors' => __d('administrator', 'Personalización de colores'),								    	              		
									    	              		'submit' => __d('administrator', 'Actualizar'),
									    	              		'info_web' => __d('administrator', 'Datos del sitio'),
									    	              		'custom_main' => __d('administrator', 'Menú principal'),
									    	              		'frontend_main_home' => __d('administrator', 'Inicio'),
									    	              		'main_home_placeholder' => __d('administrator', 'Si deseas link de inicio agrega el texto necesario'),
									    	              		'main_order' => __d('administrator', 'Organización del menú'),
									    	              		'add_menu' => __d('administrator', 'Agregar al menú'),

									    	              		'color1' => __d('administrator', 'Color claro'),
									    	              		'color2' => __d('administrator', 'Resaltados'),
									    	              		'color3' => __d('administrator', 'Textos'),
									    	              		'color4' => __d('administrator', 'Oscuros'),
									    	              		'color5' => __d('administrator', 'Adicional'),

		    	                        					),

		    	       					'custom_fields'=>array( 'title' => __d('administrator', 'Campos personalizables'),
		    	       					  						'description' => __d('administrator', 'Agrega, configura o edita los campos personalizables aquí'),	    	       						
									    	              		'new_custom_field' => __d('administrator', 'Nuevo campo personalizable'),
									    	              		'option_key' => __d('administrator', 'Nombre del campo'),
									    	              		'input' => __d('administrator', 'Tipo de campo'),
									    	              		'option_label' => __d('administrator', 'Titulo del campo'),
									    	              		'option_value' => __d('administrator', 'Caracteristicas del campo'),
									    	              		'options' => __d('administrator', 'Opciones de campos: Select, Checkbox, radio'),
									    	              		'create' => __d('administrator', 'Crear campo'),
									    	              		'edit_custom_fields' => __d('administrator', 'Editar campos personalizados'),
									    	              		'update_fields' => __d('administrator', 'Actualizar campos'),
		    	                        					),


		    	       					'newsletter'=>array( 'title' => __d('administrator', 'Newsletter'),
		    	       					  						'description' => __d('administrator', 'Usuarios registrados para recibir noticias'),	    	       						
									    	              		'new_custom_field' => __d('administrator', 'Nuevo campo personalizable'),
									    	              		'option_key' => __d('administrator', 'Nombre del campo'),
									    	              		'input' => __d('administrator', 'Tipo de campo'),
									    	              		'option_label' => __d('administrator', 'Titulo del campo'),
									    	              		'option_value' => __d('administrator', 'Caracteristicas del campo'),
									    	              		'options' => __d('administrator', 'Opciones de campos: Select, Checkbox, radio'),
									    	              		'create' => __d('administrator', 'Crear campo'),
									    	              		'edit_custom_fields' => __d('administrator', 'Editar campos personalizados'),
									    	              		'update_fields' => __d('administrator', 'Actualizar campos'),
									    	              		'trash_restore' => __d('administrator', 'Mover a papelera'),
									    	              		
		    	                        					),


		    	       			),

						// publicaciones
		    	       'Posts' => array('index' =>   array(		'title' => __d('administrator', 'Todas las publicaciones'),
		    	       											'description' => __d('administrator', 'Estas son todas las publicaciones disponibles en el momento'),
		    	       											'all' => __d('administrator', 'Todas las publicaciones'),
									    	              		'active' => __d('administrator', 'Publicaciones activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'Publicaciones inactivas'),
									    	              		'trash_restore' => __d('administrator', 'Mover a papelera'),
									    	              		'controller' => __d('administrator', 'publicaciones'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),
		    	                        				    ),

		    	       					'edit' =>    array(		'title' => __d('administrator', 'Editar publicación'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega el titulo de tu publicación'),
									    	              		'description' => __d('administrator', ''),
		    	       											'excerpt' => __d('administrator', 'Texto destacado'),
									    	              		'excerpt_placeholder' => __d('administrator', 'Los desacados son resúmenes opcionales de tu contenido.'),
									    	              		'icon_description' => __d('administrator', 'Define el icono principal para esta publicación.'),
									    	              		'type_description' => __d('administrator', 'Cada tipo debe tener una vista exclusiva'),									    	              										    	              		
									    	              		'submit' => __d('administrator', 'Actualizar publicación'),								    	              		
								    	              		
		    	                        				    ),


										'add' =>    array(		'title' => __d('administrator', 'Agregar publicación'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega el titulo de tu publicación'),
									    	              		'description' => __d('administrator', ''),
		    	       											'excerpt' => __d('administrator', 'Texto destacado'),
									    	              		'excerpt_description' => __d('administrator', 'Los desacados son resúmenes opcionales de tu contenido.'),
									    	              		'icon_description' => __d('administrator', 'Define el icono principal para esta publicación.'),
									    	              		'type_description' => __d('administrator', 'Cada tipo debe tener una vista exclusiva'),									    	              										    	              		
									    	              		'excerpt_placeholder' => __d('administrator', 'Los desacados son resúmenes opcionales de tu contenido.'),
									    	              		'submit' => __d('administrator', 'Publicar'),								    	              		
								    	              		
		    	                        				    ),


		    	       					'trash' =>   array(		'title' => __d('administrator', 'Publicaciones inactivas'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas las publicaciones'),
									    	              		'active' => __d('administrator', 'Publicaciones activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'Publicaciones inactivas'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),
									    	              		'trash_restore' => __d('administrator', 'Restaurar publicaciones'),
		    	                        				    ),

		    	       				),

					
					// Páginas
		    	       'Pages' => array('index' =>   array(		'title' => __d('administrator', 'Todas las páginas'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas las páginas'),
									    	              		'active' => __d('administrator', 'páginas activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'páginas inactivas'),
									    	              		'trash_restore' => __d('administrator', 'Mover a papelera'),
									    	              		'controller' => __d('administrator', 'páginas'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),
		    	                        				    ),

		    	       					'edit' =>    array(		'title' => __d('administrator', 'Editar página'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega el titulo de tu página'),
									    	              		'description' => __d('administrator', ''),
		    	       											'excerpt' => __d('administrator', 'Texto destacado'),
									    	              		'excerpt_placeholder' => __d('administrator', 'Los desacados son resúmenes opcionales de tu contenido.'),
									    	              		'icon_description' => __d('administrator', 'Define el icono principal para esta página.'),								    	              		
									    	              		'type_description' => __d('administrator', 'Cada tipo debe tener una vista exclusiva'),								    	              		
									    	              		'submit' => __d('administrator', 'Actualizar página'),
									    	              		'gadget_description' => __d('administrator', 'Selecciona un gadget de ser necesario, si tu tema lo soporta aparecerá en la página.'),								    	              		
								    	              		
		    	                        				    ),


										'add' =>    array(		'title' => __d('administrator', 'Agregar página'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega el titulo de tu página'),
									    	              		'description' => __d('administrator', ''),
		    	       											'excerpt' => __d('administrator', 'Texto destacado'),
									    	              		'excerpt_placeholder' => __d('administrator', 'Los desacados son resúmenes opcionales de tu contenido.'),
									    	              		'icon_description' => __d('administrator', 'Define el icono principal para esta páginas.'),
									    	              		'type_description' => __d('administrator', 'Cada tipo debe tener una vista exclusiva'),								    	              		
									    	              		'submit' => __d('administrator', 'Publicar'),		
									    	              		'gadget_description' => __d('administrator', 'Selecciona un gadget de ser necesario, si tu tema lo soporta aparecerá en la página.'),		    	              		
								    	              		
		    	                        				    ),


		    	       					'trash' =>   array(		'title' => __d('administrator', 'Publicaciones inactivas'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas las páginas'),
									    	              		'active' => __d('administrator', 'páginas activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'páginas inactivas'),
									    	              		'trash_restore' => __d('administrator', 'Restaurar páginas'),
									    	              		'controller' => __d('administrator', 'publicaciones'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),
		    	                        				    ),

		    	       				),

						
						// Categorias
		    	       'Categories' => array('index' =>  array(	'title' => __d('administrator', 'Todas las categorías'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas las categorías'),
									    	              		'active' => __d('administrator', 'categorías activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'categorías inactivas'),
									    	              		'trash_restore' => __d('administrator', 'Mover a papelera'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),									    	              		
									    	              		'controller' => __d('administrator', 'categorías'),

		    	                        					),

		    	       					    'trash' =>array(	'title' => __d('administrator', 'Todas las categorías'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas las categorías'),
									    	              		'active' => __d('administrator', 'categorías activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'categorías inactivas'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),	
									    	              		'trash_restore' => __d('administrator', 'Mover a papelera'),							    	              		
		    	                        					),

		    	       					'edit' =>     array( 	'title' => __d('administrator', 'Editar categoría'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega el titulo de tu categoría'),
									    	              		'description' => __d('administrator', 'Edita los textos e imágenes de esta categoría'),
		    	       											'up_categories' => __d('administrator', 'Categoría superior'),
									    	              		'type_description' => __d('administrator', 'Cada tipo debe tener una vista exclusiva'),								    	              		
									    	              		'submit' => __d('administrator', 'Actualizar categoría'),							    	              		
		    	                        					),

		    	       					'add' =>	  array(    'title' => __d('administrator', 'Agregar categoría'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega el titulo de tu categoría'),
		    	       											'description' => __d('administrator', ''),
		    	       											'up_categories' => __d('administrator', 'Categoría superior'),
									    	              		'type_description' => __d('administrator', 'Cada tipo debe tener una vista exclusiva'),								    	              		
									    	              		'submit' => __d('administrator', 'Generar categoría'),			    	                        					
									    	              	),
		    	       				),


						// Categorias
		    	       'Archives' => array('index' =>  array(	'title' => __d('administrator', 'Archivos'),
		    	       											'description' => __d('administrator', ''),
		    	       											'trash_restore' => __d('administrator', 'Mover a papelera'),
		    	       											'all' => __d('administrator', 'Todos'),
		    	       											'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),
									    	              		'active' => __d('administrator', 'Activos'),								    	              		
									    	              		'inactive' => __d('administrator', 'Rotos'),		    	       											
		    	                        					),

		    	       					'trash' =>  array(	'title' => __d('administrator', 'Archivos multimedia'),
		    	       											'description' => __d('administrator', 'Desde estas sección puedes editar archivos multimedia o eliminar los archivos que ya no necesitas.'),
		    	       											'trash_restore' => __d('administrator', 'Mover a papelera'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas las categorías'),
									    	              		'active' => __d('administrator', 'categorías activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'categorías inactivas'),		    	       											
		    	                        					),

		    	       					    
		    	       					'edit' =>     array( 	'title' => __d('administrator', 'Editar Imagen'),
		    	       											'title_placeholder' => __d('administrator', 'Agrega un titulo a la imagen'),
									    	              		'description' => __d('administrator', ''),
		    	       											'up_categories' => __d('administrator', 'Categoría superior'),
									    	              		'type_description' => __d('administrator', 'Cada tipo debe tener una vista exclusiva'),								    	              		
									    	              		'submit' => __d('administrator', 'Actualizar Imagen'),
									    	              		'delete' => __d('administrator', 'Eliminar Imagen'),							    	              		
		    	                        					),

		    	       				),

						'SellRent' => array('index' =>  array(	'title' => __d('administrator', 'Ofertas'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas'),
									    	              		'active' => __d('administrator', 'Activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'Inactivas'),
									    	              		'trash_restore' => __d('administrator', 'Establecer como inactivas'),
									    	              		'controller' => __d('administrator', 'Ofertas'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),
		    	                        					),

		    	       					    
		    	       					'offer_rent' =>  array(	'title' => __d('administrator', 'Ofertas para alquiler'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas'),
									    	              		'active' => __d('administrator', 'Activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'Inactivas'),
									    	              		'trash_restore' => __d('administrator', 'Establecer como inactivas'),
									    	              		'controller' => __d('administrator', 'Ofertas'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),
		    	                        					),

		    	       					'offer_sell' =>  array(	'title' => __d('administrator', 'Ofertas para la venta'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas'),
									    	              		'active' => __d('administrator', 'Activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'Inactivas'),
									    	              		'trash_restore' => __d('administrator', 'Establecer como inactivas'),
									    	              		'controller' => __d('administrator', 'Ofertas'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),
		    	                        					),


		    	       					'view' =>  array(	'title' => __d('administrator', 'Datos de la oferta'),
									    	              	'description' => __d('administrator', 'Estas son las alertas que generó esta oferta'),
		    	                        					),


		    	       					'trash' =>  array(	'title' => __d('administrator', 'Ofertas inactivas'),
		    	       											'description' => __d('administrator', ''),
		    	       											'all' => __d('administrator', 'Todas'),
									    	              		'active' => __d('administrator', 'Activas'),								    	              		
									    	              		'inactive' => __d('administrator', 'Inactivas'),
									    	              		'trash_restore' => __d('administrator', 'Cambiar a activas'),
									    	              		'controller' => __d('administrator', 'Ofertas'),
									    	              		'table_name' => __d('administrator', 'Nombre'),
									    	              		'table_description' => __d('administrator', 'Descripción'),
		    	                        					),


		    	       				),
		    	       			    
		    	    						
		    	 );

		return @array($controlador => $text[$controlador][$vista], 'Extras' => $text['Extras'], 'Images' => $text['Images']);

        }
}

?>